spring:
  application:
    name: CONFIG-SERVICE-DEV
  datasource:
    url: jdbc:mysql://localhost:3306/springrest
    username: root
    password: Md7$#1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  



eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/ 
